name: Test suite

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: "0 2 * * 1-5"
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Compile the blink crate with Rust nightly
      run: docker build . --file Dockerfile.ci --tag avr-rust/blink.ci:$(date +%s)
